# NumPy Array Iterating

In [1]:
#Nested for loop for 2-D array

import numpy as np

arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

for row in arr:
    for items in row:
        print(items)

1
2
3
4
5
6
7
8


In [2]:
#1-D Array

arrOne = np.array([2, 5, 9, 7])

for items in arrOne:
    print(items)

2
5
9
7


In [3]:
#3-D Array

arrThree = np.array([
    [
        [5, 5, 6, 6],
        [7, 7, 4, 4]
    ],
    [
        [1, 2, 2, 1],
        [3, 3, 0, 0]
    ]
])

for row in arrThree:
    for x in row:
        for y in x:
            print(y)

5
5
6
6
7
7
4
4
1
2
2
1
3
3
0
0


# NumPy Array Slicing

* [:end] : 0 to end
* [start:end] : start to end
* [start:] : start to last index
* [::step] : start to end increment of step
* [start:end:step]

In [9]:
import numpy as my

arr = my.array([1, 12, 2, 22, 3, 34, 5, 6, 7, 8, 9])

sliced = arr[:3] #[:end] : 0 to end

print(sliced)

[ 1 12  2]


In [10]:
sliced1 = arr[3:7] #[start:end] : start to end

print(sliced1)

[22  3 34  5]


In [12]:
sliced2 = arr[6:] #[start:] : start to last index

print(sliced2)

[5 6 7 8 9]


In [13]:
sliced3 = arr[::2] #[::stop] : start to end increment of step

print(sliced3)

[1 2 3 5 7 9]


In [14]:
sliced4 = arr[1:8:3] #[start:end:step]

print(sliced4)

[12  3  6]


In [15]:
sliced5 = arr[1:8]

print(sliced5)

[12  2 22  3 34  5  6]


In [24]:
# 2-D array slicing

arrD = my.array([
    [5, 4, 3, 2],
    [1, 2, 3, 4],
    [4, 8, 9, 2]
])

#Slicing row
row = arrD[0:2]
print(row)

print("\n")

#Slicing column
col = arrD[:, 1:3]
print(col)

[[5 4 3 2]
 [1 2 3 4]]


[[4 3]
 [2 3]
 [8 9]]


In [25]:
#1st 2rows & col 2 & 3

matrix = arrD[:2, 1:3]

print(matrix)

[[4 3]
 [2 3]]
