# Import NumPy

In [1]:
import numpy as np

#Accessing numpy library using np
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# Checking NumPy version

In [2]:
print(np.__version__)

1.24.3


# Numpy Creating Arrays

In [3]:
arr = np.array([4, 8, 16, 32, 64])

print(arr)
print(type(arr))

[ 4  8 16 32 64]
<class 'numpy.ndarray'>


# Dimension in Arrays

In [4]:
#0-D array

arr = np.array(5)

print(arr)
print(arr.ndim)

5
0


In [5]:
#1-D array

arr1 = np.array([1, 0, 1, 0])

print(arr1)
print(arr1.ndim)

[1 0 1 0]
1


In [6]:
#2-D array

arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [8]:
#3-D array

arr3 = np.array([
    [
        [5, 8, 6],
        [7, 2, 4]
    ],
    [
        [4, 2, 9],
        [3, 3, 2]
    ]
])

print(arr3)
print(arr3.ndim)

[[[5 8 6]
  [7 2 4]]

 [[4 2 9]
  [3 3 2]]]
3


In [11]:
print(type(arr))
print(type(arr1))
print(type(arr2))
print(type(arr3))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


# NumPy Array Shape

In [12]:
print(arr.shape)
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

()
(4,)
(2, 3)
(2, 2, 3)


# NumPy Array Reshaping

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

#Re-shaping array into 2-D array

re_shaped_arr = arr.reshape(2, 3)

print(re_shaped_arr)

[[1 2 3]
 [4 5 6]]


# NumPy Array Indexing

In [15]:
arr = np.array([4, 5, 7, 9])

print(arr[0])
print(arr[0]+arr[3])

4
13


In [16]:
#Access 2-D Array

arr2 = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

print(arr2[0, 2])

3


In [17]:
#Access 3-D Array

arr3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 11]
    ]
])

print(arr3[0, 0, 2])
print(arr3[1, 0, 0])

3
7


In [18]:
#Negative indexing

ar = np.array([
    [5, 6, 7, 10],
    [4, 9, 8, 12]
])

print(ar[0, -2])
print(ar[1, -1])

7
12
