# Reshapping Arrays

In [1]:
# Load library
import numpy as np

# Create a 4*3 matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])

# Reshape matrix to 2*6 matrix
reshaped_matrix = matrix.reshape(2, 6)

In [2]:
reshaped_matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [5]:
new_shaped_matrix = matrix.reshape(1, -1)

In [6]:
new_shaped_matrix

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [7]:
matrix.size

12

# Transposing

In [12]:
# Load library
import numpy as np
my_matrix = np.array([[4, 5, 6],
                    [2, 3, 9]])

# Transpose the matrix
my_matrix.T

array([[4, 2],
       [5, 3],
       [6, 9]])

In [13]:
my_matrix.flatten()

array([4, 5, 6, 2, 3, 9])

# Adding, Sbtract, Multiplying

In [15]:
# Adding
matrix_a = np.array([[1, 1, 1],
                    [1, 1, 1],
                    [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                    [1, 3, 1],
                    [1, 3, 8]])

matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [16]:
# Subtracting
matrix_a - matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [18]:
# Multiplying
matrix_a * matrix_b

array([[ 1,  3,  1],
       [ 1,  3,  1],
       [ 1,  3, 16]])

# Generating random values

In [24]:
# General method
np.random.uniform(low = 0, high = 100, size = 10)

array([57.61573344, 59.20419313, 57.22519058, 22.30816326, 95.27490115,
       44.71253786, 84.64086725, 69.94792753, 29.74369509, 81.37978197])

In [20]:
# Pseudorandom values

# Load library
import numpy as np

# Set seed
np.random.seed(0)

# Generate three random floats between 0.0 & 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [22]:
# Generate three random integers between 0 & 10
np.random.randint(0, 10, 3)

array([7, 9, 3])