# Descriptive Statistics
* Mean
* Median
* Variance
* Standard Deviation

In [2]:
import numpy as np

data = np.arange(20, 35)

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_deviance = np.std(data)

In [3]:
print(mean)
print(median)
print(variance)
print(std_deviance)

27.0
27.0
18.666666666666668
4.320493798938574


# Handling Missing Values

In [4]:
# checking for NAN values

arr = np.array([1, 2, np.nan, 4, 5, np.nan])

nan_checker = np.sum(np.isnan(arr))

nan_checker

2

In [5]:
# Removing NAN values

cleaner = arr[~np.isnan(arr)]

cleaner

array([1., 2., 4., 5.])

In [6]:
mean = np.nanmean(arr)

data_filled = np.where(np.isnan(arr), mean, arr)

data_filled

array([1., 2., 3., 4., 5., 3.])

# Array of Zeroes

In [8]:
mini = np.zeros(5)

In [9]:
mini

array([0., 0., 0., 0., 0.])

In [10]:
small = np.ones(2)
small

array([1., 1.])