# Numpy Data Types

In [2]:
#checking data types
import numpy as nm
arr = nm.array([1, 2, 3, 4])

arr2 = nm.array([4.5, 3.4, 3.9, 4.2])

print(arr2, arr2.dtype)
print("\n")
print(arr, arr.dtype)

[4.5 3.4 3.9 4.2] float64


[1 2 3 4] int32


In [4]:
#assigning data type
arrays = nm.array([1, 2, 3, 4], dtype = nm.float64)

arrays2 = nm.array([4.5, 3.4, 3.9, 4.2], dtype = nm.int32)

print(arrays2, arrays2.dtype)
print("\n")
print(arrays, arrays.dtype)


[4 3 3 4] int32


[1. 2. 3. 4.] float64


In [6]:
#converting data types

old_arr = nm.array([4.5, 7.2, 9.1])

arr_int = arr.astype(nm.int32)

print(arr_int.dtype)

int32


# Joining NumPy Arrays

In [7]:
arr1 = nm.array([5,4,3,2,1])
arr2 = nm.array([2,3,4,5,6])

result = nm.concatenate((arr1, arr2)) #concatenate

In [8]:
print(result)

[5 4 3 2 1 2 3 4 5 6]
