# Splitting NumPy Arrays

In [4]:
#Creating dtata using arrange

import numpy as np

arr = np.arange(1,26)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [5]:
split_arr = np.split(arr, 5)

In [6]:
print(split_arr)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15]), array([16, 17, 18, 19, 20]), array([21, 22, 23, 24, 25])]


In [9]:
#Unequla Splitting

unequal_split_arr = np.array_split(arr, 2)

In [10]:
unequal_split_arr

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13]),
 array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])]

# NumPy searching Arrays

In [13]:
my_array = np.arange(58, 72)

index = np.where(my_array > 65)
print(my_array)
index

[58 59 60 61 62 63 64 65 66 67 68 69 70 71]


(array([ 8,  9, 10, 11, 12, 13], dtype=int64),)

In [15]:
his_array = np.array([75, 84, 21, 20, 1, 0, 99])

checker = np.where(his_array > 20)

checker

(array([0, 1, 2, 6], dtype=int64),)

# Array masking

In [17]:
arrr = np.array([72, 62, 14, 75])

mask = arrr>14

filtered_value = arrr[mask]

filtered_value

array([72, 62, 75])

# Array Sorting

In [18]:
unsorted_arr = np.array([54, 32, 75, 85, 9])

sorted_arr = np.sort(unsorted_arr)

sorted_arr

array([ 9, 32, 54, 75, 85])

In [19]:
ulta_arr = np.arange(75, 90)

ulta_sort = np.sort(ulta_arr)[::-1]

ulta_sort

array([89, 88, 87, 86, 85, 84, 83, 82, 81, 80, 79, 78, 77, 76, 75])

In [20]:
# axis-1 (Sorting along rows)

arr1 = np.array([
    [45, 65, 78, 1],
    [88, 22, 64, 3]
])

my_sort = np.sort(arr1, axis = 1)

my_sort

array([[ 1, 45, 65, 78],
       [ 3, 22, 64, 88]])

In [21]:
# axis-0 (Sorting along cols)

arr2 = np.array([
    [45, 65, 78, 1],
    [88, 22, 64, 3]
])

my_new_sort = np.sort(arr2, axis = 0)

my_new_sort

array([[45, 22, 64,  1],
       [88, 65, 78,  3]])

# MAT125 operations

In [22]:
arrOne = np.array([78, 55, 36, 11])
arrTwo = np.array([2, 1, 2, 1])

adder = arrOne + arrTwo

adder

array([80, 56, 38, 12])

In [23]:
arrOne = np.array([78, 55, 36, 11])
arrTwo = np.array([2, 1, 2, 1])

multiply = arrOne * arrTwo

multiply

array([156,  55,  72,  11])

In [24]:
arrOne = np.array([78, 55, 36, 11])
arrTwo = np.array([2, 1, 2, 1])

division = arrOne / arrTwo

division

array([39., 55., 18., 11.])

In [25]:
arrOne = np.array([78, 55, 36, 11])
arrTwo = np.array([2, 1, 2, 1])

result = arrOne - arrTwo

adder

array([80, 56, 38, 12])

In [26]:
arrOne = np.array([78, 55, 36, 11])
arrTwo = np.array([2, 1, 2, 1])

sqrt = np.sqrt(arrTwo)

sqrt

array([1.41421356, 1.        , 1.41421356, 1.        ])

In [28]:
arrRandom = np.array([
    [5, 4, 3, 2],
    [1, 2, 3, 4]
])

scaler = arrRandom + 10

scaler

array([[15, 14, 13, 12],
       [11, 12, 13, 14]])

In [29]:
rowToAdd = arrRandom + np.array([5, 5, 1, 1])

rowToAdd

array([[10,  9,  4,  3],
       [ 6,  7,  4,  5]])