# Creating a Vector

In [1]:
# Need to reate a vector
# Load the library
import numpy as np

#Creating a vector as a row
vector_row = np.array([1,2,3])

#Creating a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

In [2]:
vector_row

array([1, 2, 3])

In [3]:
vector_column

array([[1],
       [2],
       [3]])

# Creating a Matrix

In [4]:
# Load the library
import numpy as np

# Create matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

In [5]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

# Creating a Sparse Matrix

In [6]:
# Load library
import numpy as np
from scipy import sparse

# Create Matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])
# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [7]:
matrix

array([[0, 0],
       [0, 1],
       [3, 0]])

In [9]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [12]:
# Creating larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0]])

from scipy import sparse
# Compressed Sparse Row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

print(matrix_large_sparse)

  (1, 1)	1
  (2, 8)	3


# Selecting Elements

In [13]:
# Load library
import numpy as np

# Create row vector
vector = np.array([1, 2, 3, 4, 5])

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

vector[3]

4

In [14]:
matrix[1, 1]

5

In [15]:
## Select all elements of vector
vector[:]

array([1, 2, 3, 4, 5])

In [16]:
## Select up to x elements of vector
vector[:3]

array([1, 2, 3])

In [17]:
## Select after the x elements of vector
vector[3:]

array([4, 5])

In [18]:
## Select the last element
vector[-1]

5

In [19]:
# Select the forst two rows & all columns of a matrix
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# Select all rows & the second column
matrix[:, 1:2]

array([[2],
       [5],
       [8]])

# Describing a Matrix

In [22]:
# Shape
import numpy as np

my_matrix = np.array([[1, 3, 7, 9],
                     [11, 13, 15, 19],
                     [2, 4, 5, 6]])

# View number of rows & column
my_matrix.shape

(3, 4)

In [23]:
# View number of elements (rows * columns)
my_matrix.size

12

In [24]:
# View the dimension
my_matrix.ndim

2

# Broadcasting operation

In [25]:
my_matrix + 100

array([[101, 103, 107, 109],
       [111, 113, 115, 119],
       [102, 104, 105, 106]])

# Max, Min, Avg, Variance, Std

In [26]:
# Return maximum element
np.max(my_matrix)

19

In [27]:
# Return minimum element
np.min(my_matrix)

1

In [34]:
# Find max in each row
np.max(my_matrix, axis = 1)

array([ 9, 19,  6])

In [35]:
# Find min in each column
np.min(my_matrix, axis = 0)

array([1, 3, 5, 6])

In [30]:
# Return mean
np.mean(my_matrix)

7.916666666666667

In [31]:
# Return variance
np.var(my_matrix)

28.743055555555554

In [32]:
# Return Standard Deviation
np.std(my_matrix)

5.361255035488943

In [36]:
# Return mean value in each column
np.mean(my_matrix, axis = 0)

array([ 4.66666667,  6.66666667,  9.        , 11.33333333])